version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh node ./src/index.js
    networks:
      - hello-network
    volumes:
      - ./app:/home/app
      - /home/app/node_modules
    tty: true
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - hello-network
    ports:
      - 8080:80
    depends_on:
      - app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER=toor
      - MYSQL_PASSWORD=toor
    networks:
      - hello-network

networks:
  hello-network:
    driver: bridge